name: buf
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: bufbuild/buf-setup-action@v1
      with:
        version: "1.28.1"
        buf_api_token: ${{ secrets.BSR_TOKEN }}
        buf_user: ${{ secrets.BSR_USER }}
        github_token: ${{ github.token }}
    - uses: bufbuild/buf-lint-action@v1
    - uses: bufbuild/buf-breaking-action@v1
      with:
        against: https://github.com/${GITHUB_REPOSITORY}.git#branch=master
    - uses: bufbuild/buf-push-action@v1
      with:
        buf_token: ${{ secrets.BSR_TOKEN }}
        draft: ${{ github.ref_name != 'master'}}
